### ISSUE TITLE
need updated tag for deprecating v1_1

### ISSUE THREAD

**Issue by gtmanfred** [rackerlabs/os_diskconfig_python_novaclient_ext#6]
@rgbkrk do you know who owns this one on pypi?

This is the last plugin with the following error.

```
/usr/lib/python2.7/site-packages/novaclient/v1_1/__init__.py:30: UserWarning: Module novaclient.v1_1 is deprecated (taken as a basis for novaclient.v2). The preferable way to get client class or object you can find in novaclient.client module.
  warnings.warn("Module novaclient.v1_1 is deprecated (taken as a basis for "
```

**Comment by rgbkrk** [comment]
Looks like @rconradharris and @jerdfelt, from what https://pypi.python.org/pypi/os_diskconfig_python_novaclient_ext lists.

@rconradharris or @jerdfelt: you prepped to support these or would you be able to add @gtmanfred or I to the owners on PyPI?

**Comment by rgbkrk** [comment]
Blocking https://github.com/rackspace/pyrax/pull/547 at the moment, we'll get this administratively overridden this week.

**Comment by jimrollenhagen** [comment]
I've just uploaded 0.1.3 to pypi with a fix for this.

/cc @rgbkrk @gtmanfred

**Comment by rgbkrk** [comment]
Thank you!

**Comment by gtmanfred** [comment]
Awesome!
